### ISSUE TITLE
Search results are showing HTML code again

### ISSUE THREAD

**Issue by curiousdannii** [kripken/emscripten-site#12]
Same as last time: https://github.com/emscripten-core/emscripten/issues/6452

Last time you said you needed to include "the sources". Don't really know what that means though.

**Comment by kripken** [comment]
Thanks @curiousdannii !

That's weird, I don't think we changed anything... I re-added `_sources/` now. Once github pages processes it hopefully things work again.

Did we change anything there @sbc100 ? I don't remember anything.

**Comment by curiousdannii** [comment]
Looks like it's fixed now! 😄

**Comment by kripken** [comment]
Great, closing.

**Comment by sbc100** [comment]
I haven't committed anything to the gh-pages in a very long time.
