### ISSUE TITLE
first book w/ Emscripten published

### ISSUE THREAD

**Issue by nickdesaulniers** [kripken/emscripten-site#5]
Desaulniers, N. (2015). Emscripten and WebGL. In P. Cozzi, WebGL Insights (pp. 71-88). Boca Raton, Florida: A K Peters/CRC Press. Amazon CRC Press

Chapter 5: Emscripten and WebGL

https://www.crcpress.com/WebGL-Insights/Cozzi/9781498716079
http://www.amazon.com/WebGL-Insights-Patrick-Cozzi/dp/1498716075/

**Comment by kripken** [comment]
Added to http://kripken.github.io/emscripten-site/docs/introducing_emscripten/Talks-and-Publications.html
