### ISSUE TITLE
Make gh-pages the default branch for this repo, delete master

### ISSUE THREAD

**Issue by aidanhs** [kripken/emscripten-site#6]
Helps prevent confusion.

**Comment by Croydon** [comment]
+1

**Comment by kripken** [comment]
I made gh-pages the default branch. Would it still be beneficial to delete master? Is that even safe? :)

**Comment by Croydon** [comment]
I just did this in another repo, looks fine for me. I also saw multiple repos with no master branch, so it should be safe :)

**Comment by kripken** [comment]
Ok, thanks, done.
