### ISSUE TITLE
missing document

### ISSUE THREAD

**Issue by lucyllewy** [kripken/emscripten-site#8]
the Pthreads document, which is seemingly supposed to be at https://kripken.github.io/emscripten-site/docs/porting/pthreads.html appears to be missing. It is linked in the menu on the left-hand side of the site under the parent "Porting" and labelled as "Pthreads support". The link leads to a github 404 page :-(

**Comment by kripken** [comment]
Fixed, thanks. Was indeed a missing file, had to just git add and push it.
